### PR TITLE
Add library target  + Add parsing of UBX_NAV_TIMELS and UBX_MON_RF

### PR DESCRIPTION
**Pull request by CharlesParent**
We use the program as a library in an Open source project to get data from a GNSS serial.

First thank you a lot for all your work, it has been very useful !

We added some functionnalities and build targets:

- Library target to create a shared library that can be called  by any program
- We added parsing of UBX_NAV_TIMELS and UBX_MON_RF to get respectively leap second data and antenna status

### CODE REVIEW

**Comment by phkehl** [comment]
Hi Charles

Awesome. Many thanks! I have a few comments:

- Why do you add UBX-MON-RF into the epoch detection? The whole epoch thing is supped to be UBX-NAV-* only (hence the early return in epochCollect() (resp. _detectUbx()). Because only those UBX-NAV messages have the iTOW, which lets us unambiguously collect the matching parts of an epoch into one consistent epoch. The epoch-complete detection works by either seeing a UBX-NAV-EOE marker (which may or may not be enabled on the receiver) or by seeing  a change in time (iTOW for UBX, or UTC time in NMEA [not yet implemented, but foreseen]). The UBX-MON-RF cannot (must not) be used to detect an epoch. What was your idea here?
- Similarly, collecting non-UBX-NAV info (here, UBX-MON-RF) into the epoch struct isn't what the (granted, mostly undocumented) epoch concept foresees. The problem is that the UBX-MON-RF stuff isn't navigation epoch data and on the receiver runs completely independent from navigation. For example, if nav runs at > 1Hz the UBX-MON stuff still runs at 1 Hz and you'll only have the information every other epoch or so. Also, the order of output is not guaranteed. Could you live with collecting this info separately (in your application) instead of in the epoch code? I'll have to meditate a bit more about this, but my current conclusion is that this should not be in epoch.
- The leap second stuff is good and useful. Thanks for adding it.
- I think you should add a "Copyright ... Charles ..." to the .c and .h files you changed. Credits where credits is due!

Again, many thanks for contributing! It's really nice to see this library being used somewhere else. Can you share which project this is used in?

Best regards,
flipflip

**Comment by CharlesParent** [comment]
Hello flipflip,

Thank you very much for you feedback !

To tell you more about project. I am working on a solution to discipline the 10MHz output of a Rubidium oscillator to the 1PPS output of a GNSS receiver. 

The goal is to provide a Timing PCI card that would expose a PHC disciplined to a GNSS reference that can be used as a PTP grand master.
The whole project is part of [OCP's Time Applicance Project]( https://github.com/opencomputeproject/Time-Appliance-Project).
I will open source all the code using ubloxcfg by the end of next week and will send you the links :)


- I added UBX_MON_RF because I need the antenna status to know if software discplining program should go into Holdover mode (oscillator is then in free-run and is not disciplined anymore). I have not foresee the issue because i am setting all the messages to a 1Hz frequency
- I aggree with you, Epoch Collect might not be the best place to fetch non UBX-NAV message. Do you think we should implement another collect mechanism (like monitor collect) to collect monitoring data about the gnss chip ?

- I will add the credits next week as well, thanks for reminding me !

Best regards,

Charles

**Comment by phkehl** [comment]
Hi Charles

The epoch should really only be navigation solution information. This abstraction and normalisation (to SI units, signal type enum, etc.) could also be done with input from different GNSS receivers (or standard NMEA sentences). So I want to restrict the contents of the epoch struct to this.

The monitoring messages on the other hand are very specific to u-blox receivers. (Other receivers have similar messages, sometimes "inspired" by u-blox messages I think). Looking at the UBX-MON-* messages I see not much data from different messages that would benefit from an abstraction and normalisation into a new struct. Each of the UBX-MON messages is pretty much self-contained and doesn't "group" with any other UBX-MON message.

Therefore I propose to change your patch as follows:

- Remove any UBX-MON-RF stuff from the epoch code (but keep the good UBX-NAV-TIMLS stuff)
- Use UBX-MON-RF (UBX_MON_RF_V0_GROUP1_t struct) directly in your application (and create the necessary abstraction or normalisation on that level).

Is that acceptable for you?

Btw, to check antStatus and antPower it should be enough to look at the fields of the first group repetition in UBX-MON-RF. There is only one antenna supervisor and power control for the entire receiver, this is not per RF block. On the other hand, the interface doesn't really specify that, so checking both and assuming the worst maybe is a good idea. :-)

Regards,
flipflip

**Comment by CharlesParent** [comment]
Hello flipflip !

- I removed any UBX-MON-RF related code from epoch code
- I found a way to get UBX-MON-RF directly in my program

I also added credits to files I modified, I hope I did it correctly, It's my first time doing so !
The rest of the project's code will be open sourced today or tomorrow, I will send you the links to everything at that time :)

Best regards,
Charles

**Comment by phkehl** [comment]
Hi Charles

I've done a little cleanup and some minor changes that I hope won't affect you. This is now merged.
See https://github.com/phkehl/ubloxcfg/commit/4cd9a658be8b3a7197968007bd2b08855ece6ee5 for details (of my cleanup).

Regarding that baudrate change you did in ff_port.c (which I have undone). I'm not sure why you did it, but if you want more control you should already be able to do that via non-default arguments to rxInit(). Let me know if you need help. I'd recommend to use the auto-bauding and receiver detection feature, i.e. the default arguments, though. That will make rxOpen() reliably fail in case something's wrong with the receiver.

Regarding the leapseconds event stuff: I'm not super happy with that solution resp. the fields in EPOCH_t. We're now mapping  the UBX-NAV-TIMELS fields (and their magic numbers) directly into that. (And it's not exactly navigation solution info either.)

What do you want to do with this? What info do you need? (What for?)
- Leap seconds source? Do you really need this?
- Leap seconds events? Do you really need this?
- For the source (of current as well as event), do you really need this level of detail?

I'm wondering if it maybe would be better if you would use UBX_NAV_TIMLS_V0_GROUP0_t directly? (Like the UBX_MON_RF stuff...).

Anyway, for now it's in as you coded it. I only changed all fields in epoch to "int", but that shouldn't matter I hope.
And I can not guarantee that I might too tempted to change this a bit sometimes in the future, and for example abstract the LS source into fewer states (e.g. NONE, DEFAULT, CONFIG, GNSS) or similar... :-)

Happy hacking!

Philippe

**Comment by CharlesParent** [comment]
Hi flipflip !

Thank you very much !

- Indeed I tried with the default argument and ubloxcfg is able to detect the baudrate correctly. I changed the default baudrate a long time ago when I had issue our card driver but now it's fixed. Hence it was something I forgot to remove, glad you noticed that !
- Regarding the leap second data, I only need to know the leap second events in order to fill a NTP Shared Memory some programs like chrony could use to know if a leap second is to happen. In fact we could use UBX_NAV_TIMLS_V0_GROUP0_t directly.

Thanks for you feedback, I will keep you updated about the rest of the projects when I will open-source it !

**Pull request merged**
